<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ptgol</string>
	</array>
	<key>firstLineMatch</key>
	<string>(P|p)(rograma\s*[A-Za-z][A-Za-z0-9]+)</string>
	<key>foldingStartMarker</key>
	<string>([Pp]rograma)</string>
	<key>foldingStopMarker</key>
	<string>([\*/|^\s*\}|^HTML;])</string>
	<key>name</key>
	<string>Portugol</string>
	
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>([Pp]rograma\s+[A-Za-z][A-Za-z0-9_]+)</string>
			<key>beginCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.html</string>
				</dict>
			</dict>
			<key>end</key>
			<string>(Fim\.)</string>
			<key>endCaptures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>entity.name.tag.html</string>
				</dict>
			</dict>
			<key>name</key>
			<string>meta.tag.any.html</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>"[^"]*"</string>
					<key>name</key>
					<string>string.quoted.double.doctype.identifiers-and-DTDs.html</string>
				</dict>
				<dict>
					<key>match</key>
					<string>'[^']*'</string>
					<key>name</key>
					<string>string.quoted.double.doctype.identifiers-and-DTDs.html</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b-?[0-9.]+\b</string>
					<key>name</key>
					<string>entity.name.tag.xml.html</string>
				</dict>
				<dict>
					<key>match</key>
					<string>([Pp]rograma\s+)([A-Za-z][A-Za-z0-9_]+)</string>
					<key>name</key>
					<string>entity.name.tag.html</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(Inteiro|Caractere|Real):</string>
					<key>name</key>
					<string>entity.name.tag.html</string>
				</dict>
				<dict>
					<key>match</key>
					<string>(Var|Inicio|Fim\.)[\r\n]</string>
					<key>name</key>
					<string>constant.character.entity.html</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(Escreva|Leia)\b</string>
					<key>name</key>
					<string>constant.character.entity.html</string>
				</dict>
				<dict>
					<key>match</key>
					<string>\b(Enquanto|Fim enquanto|Se|Senão|Fim se|Escolha|Caso|Fim escolha)\b</string>
					<key>name</key>
					<string>constant.character.entity.html</string>
				</dict>

				<dict>
					<key>match</key>
					<string>&lt;-</string>
					<key>name</key>
					<string>invalid.illegal.bad-comments-or-CDATA.html</string>
				</dict>
			</array>
		</dict>

	</array>
	<key>scopeName</key>
	<string>text.html.basic</string>
	<key>uuid</key>
	<string>17994EC8-6B1D-11D9-AC3A-000D93589AF6</string>
</dict>
</plist>
